variables:
  # Keep in sync with coverview-ci-files's ref
  CI_FILES_REF: "043201d6"

include:
  - project: coverview-ci-files
    file: test.yaml
    # Keep in sync with CI_FILES_REF
    ref: "043201d6"
